- README.md
- Team.psd1
- en-US/Team-Help.xml
- src/releases.psm1
- Created new function in the release module named 'Add-ReleaseEnvironment'. New function deploys an environment from an existing release.
- Created new help info for 'Add-ReleaseEnvironment' function
- Updated help info for 'Add-Release' function
> Created new function for 'Add-ReleaseEnvironment'

- Team.psd1
- src/common.ps1
- src/team.psm1
Resolve on-premise issues following recent merges; fix an issue with project validation where a user has more than 100 projects.
> Resolve on-premise issues

- src/teamspsdrive.psm1
Added new SHiPS Build Object Properties to allign with original VSTeam Build Object properties.
See issue: https://github.com/DarqueWarrior/vsteam/issues/31
> Added new Build Object Properties

- .gitignore
- en-US/about_vsteam_provider.help.txt
- src/Debugscript.txt
- src/teamspsdrive.psm1
Added new properties to SHiPS Release and Build Objects in the VSTeamPSDrive module.
> Vsteampsdrive

- .docs/Get-VSTeamTfvcBranch.md
- .docs/Get-VSTeamTfvcRootBranches.md
- .docs/synopsis/Get-VSTeamTfvcBranch.md
- .docs/synopsis/Get-VSTeamTfvcRootBranches.md
- README.md
- VSTeam.psd1
- en-US/VSTeam-Help.xml
- src/team.psm1
- src/tfvc.psm1
- types/tfvc.ps1xml
- unit/test/Approvals.Tests.ps1
- unit/test/builds.Tests.ps1
- unit/test/common.Tests.ps1
- unit/test/git.Tests.ps1
- unit/test/profile.Tests.ps1
- unit/test/projects.Tests.ps1
- unit/test/serviceendpoints.Tests.ps1
- unit/test/team.Tests.ps1
- unit/test/tfvc.Tests.ps1
- unit/test/users.Tests.ps1
Added functions for querying TFVC branches:
- Get-VSTeamTfvcRootBranches
- Get-VSTeamTfvcBranch
Based off [TFVC Branches](https://www.visualstudio.com/en-us/docs/integrate/api/tfvc/branches)
> Functions for querying TFVC branches

- .docs/Add-VSTeamServiceFabricEndpoint.md
- .docs/synopsis/Add-VSTeamServiceFabricEndpoint.md
- README.md
- VSTeam.psd1
- en-US/VSTeam-Help.xml
- integration/test/010_projects.Tests.ps1
- src/serviceendpoints.psm1
- unit/test/serviceendpoints.Tests.ps1
Adds support for creating service fabric endpoints. 
I've been using this internally for a while, and thought you might like to include it. Hopefully I have got everything in order, but it is gone midnight here, so let me know if missed anything.
> add support for creating service fabric endpoints. 

- integration/test/010_projects.Tests.ps1
fix integration test issue with #51 due to missing -endpointName parameter
> fix typo in intergration test parameters

- .docs/Add-VSTeamAccount.md
- .docs/Add-VSTeamProfile.md
- README.md
- src/team.psm1
> Fixing issue using bearer token on vsts.

- integration/test/010_projects.Tests.ps1
found and fixed 3 small typos that were distracting me in 010_projects.Tests.ps1
> fix small typos in 010_projects.Tests.ps1

- .docs/Disable-VSTeamAgent.md
- .docs/Enable-VSTeamAgent.md
- .docs/Get-VSTeamPool.md
- .docs/Remove-VSTeamAgent.md
- .docs/synopsis/Disable-VSTeamAgent.md
- .docs/synopsis/Enable-VSTeamAgent.md
- VSTeam.psd1
- docs/Get-VSTeamPool.md
- docs/Team.md
- docs/readme.md
- en-US/VSTeam-Help.xml
- formats/vsteamPSDrive.format.ps1xml
- src/agents.psm1
- src/pools.psm1
- src/teamspsdrive.ps1
- unit/test/agents.Tests.ps1
- unit/test/teamspsdrive.Tests.ps1
Next to removing agents i needed to disable them as well for my project so i added functionality to enable and disable agents in a pool. functionality was very similar to deletion of agents.
> Disable & Enable agents in pool

- CHANGELOG.md
- VSTeam.psd1
- src/Approvals.psm1
- src/buildDefinitions.psm1
- src/builds.psm1
- src/common.ps1
- src/projects.psm1
- src/releaseDefinitions.psm1
- src/releases.psm1
- src/repositories.psm1
- src/team.psm1
- src/workitems.psm1
- unit/test/Approvals.Tests.ps1
- unit/test/buildDefinitions.Tests.ps1
- unit/test/builds.Tests.ps1
- unit/test/common.Tests.ps1
- unit/test/profile.Tests.ps1
- unit/test/projects.Tests.ps1
- unit/test/release.Tests.ps1
- unit/test/releaseDefinitions.Tests.ps1
- unit/test/repositories.Tests.ps1
- unit/test/team.Tests.ps1
- unit/test/workitem.Tests.ps1
> Trackyon.utils

- CHANGELOG.md
- VSTeam.psd1
- src/team.psm1
- src/teamspsdrive.ps1
When you stored your account at the User or Admin level the version was not stored.
> Fixed bug of version not loading correctly

- .github/CONTRIBUTING.md
added install requirement for Trackyon.Utils
> added install requirement for Trackyon.Utils

- .docs/Update-VSTeamUser.md
- CHANGELOG.md
- VSTeam.psd1
- docs/Update-VSTeamUser.md
- en-US/VSTeam-Help.xml
- src/team.psm1
- src/teamspsdrive.ps1
- src/users.psm1
Set top to 10,000 when searching by email
Updated help for Update-VSTeamUser
Fixed issue where api version was not being set on load.
> Fixing issue #90

- .vsts-ci.yml
> Adding yml build

- .vsts-ci.yml
Adding conditions to steps that PRs fail on for permissions reasons.
> Adding conditions so PRs don't fail.

- .docs/Get-VSTeamPullRequest.md
- .docs/Show-VSTeamPullRequest.md
- .docs/synopsis/Get-VSTeamPullRequest.md
- .docs/synopsis/Show-VSTeamPullRequest.md
- CHANGELOG.md
- VSTeam.psd1
- docs/Team.md
- docs/readme.md
- en-US/VSTeam-Help.xml
- src/pullrequest.psm1
- types/pullrequest.ps1xml
- unit/test/pullrequest.Tests.ps1
Adding support for the Pull Request API's.
- Get-PullRequest to retrieve open pull requests
- Show-PullRequest to open the browser to view a pull request
> Adding support for Pull Request API

- src/workitems.psm1
Added more properties on a workitem. Besides title, also description/iterationpath & assignedto can be set.
> Added properties on Workitem

- src/repositories.psm1
> Fixed Get-VSTeamGitRepository to not require a project

- CHANGELOG.md
- VSTeam.psd1
- src/repositories.psm1
> Git update change log and version

- .docs/params/BuildId.md
- CHANGELOG.md
- README.md
- VSTeam.psd1
- docs/Get-VSTeamBuildArtifact.md
- docs/Get-VSTeamBuildTag.md
- docs/Update-VSTeamBuild.md
- en-US/VSTeam-Help.xml
Added Azure DevOps to readme to help with finding repo using that term.
Updated help file with the correct syntax for some functions.
- [] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
> Helpupdate

- .docs/Get-VSTeamWorkItem.md
- .docs/Update-VSTeamWorkItem.md
- .docs/synopsis/Update-VSTeamWorkItem.md
- CHANGELOG.md
- VSTeam.psd1
- docs/Add-VSTeamWorkItem.md
- docs/Get-VSTeamWorkItem.md
- docs/Team.md
- docs/readme.md
- en-US/VSTeam-Help.xml
- src/workitems.psm1
- types/workitems.ps1xml
- unit/test/workitem.Tests.ps1
Fixed bugs in Get-VSTeamWorkItem and Add-VSTeamWorkItem.
Added Update-VSTeamWorkItem
> Work Item updates

- Source/Public/Add-VSTeamProject.ps1
- Source/Public/Get-VSTeamProject.ps1
- Source/Public/Get-VSTeamUser.ps1
- Source/Public/Set-VSTeamAPIVersion.ps1
- integration/test/000_team.Tests.ps1
- integration/test/010_projects.Tests.ps1
- unit/test/users.Tests.ps1
Fixing issues with upgrading the default version of AzD accounts to 5.x.
The shape of the objects returned changed and caused integration tests to fail.
> There were failing test after  upgrading to 5.x for AzD

- CHANGELOG.md
- Source/Public/Set-VSTeamAlias.ps1
- Source/VSTeam.psd1
> Fixed typos in Set-VSTeamAlias

- README.md
> Added Hyperlink to SHiPs module to Readme.md

- Source/Public/Add-VSTeamWorkItem.ps1
- Source/Public/Update-VSTeamWorkItem.ps1
- unit/test/workitem.Tests.ps1
Is connected to the issue #196 which fixes the described problem
> bug fix for update and add workitem

- .docs/Add-VSTeamVariableGroup.md
- .docs/Update-VSTeamVariableGroup.md
- CHANGELOG.md
- Source/Public/Add-VSTeamVariableGroup.ps1
- Source/Public/Update-VSTeamVariableGroup.ps1
- Source/VSTeam.psd1
- Source/en-US/VSTeam-Help.xml
- docs/Add-VSTeamVariableGroup.md
- docs/Get-VSTeamWorkItem.md
- docs/Remove-VSTeamVariableGroup.md
- docs/Remove-VSTeamWorkItem.md
- docs/Update-VSTeamVariableGroup.md
Description is not required but was in original implementation.
> Fixed issue #208

- README.md
Rearrange readme for better visibility of key items
(not needed)
> Rearrange readme for better visibility of key items

- Build-Module.ps1
Improve Doc build to always go back to root directory even on errors
(not needed)
> Improve Doc build to always go back to root directory even on errors

- Build-Module.ps1
- CHANGELOG.md
- Source/Private/applyTypes.ps1
- Source/VSTeam.psd1
- unit/test/builds.Tests.ps1
Fix Get-VSTeamBuildArtifact with missing "properties" property
Fixes #148
> Fix Get-VSTeamBuildArtifact with missing "properties" property

- azure-pipelines.yml
Add the release to GitHub as well.
Fixes #251 
Note: You need to create a GitHub service connection named "vsteam" for this to work before merging/releasing the PR!!
(not needed)
> Add GitHub release

- CODE_OF_CONDUCT.md
- README.md
- Update to version 2.0, update contact method
- Set contact method to https://www.donovanbrown.com/contact - seems most appropriate?
Fixes #249 
(not needed IMHO)
> Update to version 2.0, update contact method

- .docs/Get-VSTeamPullRequest.md
- CHANGELOG.md
- Source/Public/Get-VSTeamPullRequest.ps1
- unit/test/pullrequest.Tests.ps1
Add filtering options to Get-VSTeamPullRequest
Fixes #154
> Add filtering options to Get-VSTeamPullRequest

- build/credscan-supression.json
Exclude Documentation and Unit Tests with Credentials from CredScan
(not needed)
> Exclude Documentation and Unit Tests with Credentials from CredScan

- Build-Module.ps1
Improve build script preventing non-working options
(not needed)
> Improve build script preventing non-working options

- azure-pipelines.yml
Get rid of build warnings from security scanners that are not run
> Get rid of build warnings

- .github/PULL_REQUEST_TEMPLATE.md
This PR fixes a wrong link in the pull request template.
> Fix link to Update CHANGELOG header

- .docs/Invoke-VSTeamRequest.md
- CHANGELOG.md
- Source/Classes/InvokeCompleter.ps1
- Source/Classes/_classes.json
- Source/Public/Invoke-VSTeamRequest.ps1
- unit/test/Invoke-VSTeamRequest.Tests.ps1
- unit/test/InvokeCompleter.Tests.ps1
- unit/test/sampleFiles/Get-VSTeamOption.json
- unit/test/sampleFiles/Get-VSTeamOption_vsrm.json
> Added InvokeCompleter for Area and Resource of ivr

- Source/VSTeam.psm1
fixes #306 . History, problem and solution is explained there.
> fixing bug for #306 - Module can't be imported in PowerShell Core 7.0
