README.md
Team.psd1
src/serviceendpoints.psm1
test/serviceendpoints.Tests.ps1

This PR has 3 parts:
* add serviceEndpoint parameters in Add-AzureRMServiceEndpoint cmdlet: if the serviceEndPoint parameters are not specified, the Automatic mode is used 
* the _trackProgress function is changed too to reflect the return code of the api (https://www.visualstudio.com/en-us/docs/integrate/api/endpoints/endpoints)
* the URL in the payload changed to https://management.azure.com

Add Service Principal parameters to the Add-AzureRMServiceEndpoint cmdlet

---

README.md
Team.psd1
src/team.psm1

A simple fix in case someone provides an account without protocol (account.visualstudio.com) or if the name includes http (for example myhttpaccount as account name)

Adding a regular expression to validate VSTS account

---

Team.psd1
src/teammembers.psm1
src/teams.psm1
src/types.ps1xml
test/teammembers.Tests.ps1
test/teams.Tests.ps1

- Added support for creating / deleting / updating teams
- Added support for getting team members

Add support for teams

---

src/teammembers.psm1

Add ProjectName as a property on team member so it can be used further down the pipeline.
For example:
`Get-Project | Get-Team | Get-TeamMember | select projectName,team,displayName | Sort-Object -Property ProjectName,Team,displayName`
This now gives a useful overview of team members in each team project / team in an account.

Add ProjectName as a property on team member so it can be used further down the pipeline

---

Team.psd1
src/TeamTypes.Artifacts.format.ps1xml
src/builds.psm1
src/types.ps1xml
test/builds.Tests.ps1

Added Support for Build Tags.
Added the ability to update KeepForever, and the Build Number
Added the ability to pull artifact data from the build.

Added support for Build Tags, Build Artifacts, and Updating Build Values.

---

README.md
VSTeam.psd1
src/serviceendpoints.psm1
unit/test/serviceendpoints.Tests.ps1

If and endpoint creation failed, the status of the endpoint is kept at $false and the _trackProgress method never ends.
If the status is $false, I add a check on the operational status to verify if the creation is still in progress. If there is a failure I write the failure message on the error output

Remove deadlock when endpoint creation failed

---

.docs/Add-VSTeamPolicy.md
.docs/Get-VSTeamPolicy.md
.docs/Get-VSTeamPolicyType.md
.docs/Remove-VSTeamPolicy.md
.docs/Update-VSTeamPolicy.md
.docs/gen-help.ps1
.docs/synopsis/Add-VSTeamPolicy.md
.docs/synopsis/Get-VSTeamPolicy.md
.docs/synopsis/Get-VSTeamPolicyType.md
.docs/synopsis/Remove-VSTeamPolicy.md
.docs/synopsis/Update-VSTeamPolicy.md
VSTeam.psd1
en-US/VSTeam-Help.xml
formats/policies.ps1xml
src/policies.psm1
types/policies.ps1xml
unit/test/policies.Tests.ps1

Adds functions for getting and editing code policies such as 'Minimum number of reviewers'.

Add functions to get/edit code policies

---

integration/test/010_projects.Tests.ps1
src/serviceendpoints.psm1
src/team.psm1
unit/test/serviceendpoints.Tests.ps1

as per @DarqueWarrior  comment on #52, this prevents TFS2017 accounts from using the service farbic endpoint cmdlet, as it is not supported.

handle unsupported api for service fabric endpoints

---

README.md
VSTeam.psd1
integration/test/010_projects.Tests.ps1

VSTS now has 6 agent pools / queues which breaks the integration test

adapt integration test to additional VSTS pool 'Hosted Ubuntu 1604'

---

.docs/Update-VSTeamProfile.md
.docs/synopsis/Update-VSTeamProfile.md
CHANGELOG.md
README.md
VSTeam.psd1
docs/Team.md
docs/readme.md
en-US/VSTeam-Help.xml
integration/test/000_team.Tests.ps1
integration/test/010_projects.Tests.ps1
src/common.ps1
src/profile.psm1
unit/test/profile.Tests.ps1

I had to revoke a lot of personal access tokens and had to update my profiles. This function allows me to just update the PAT and not the rest of the information.

Adding Update-VSTeamProfile.

---

src/users.psm1

When updating a user by id, the old license was not set and an exception was raised when emitting the  "Updated user license for $( $user.userName ) ($( $user.email )) from ($licenseOld) to ($License)" message.

old license was not populated when updating a user by id

---

CHANGELOG.md
VSTeam.psd1
src/builds.psm1
unit/test/builds.Tests.ps1

Fixed bug with add-vsteambuild

Fixed add-vsteambuild bug with build definition name.

---

src/common.ps1

Response could be null causing StatusCode to not be populated.
Minor change to verify the Response is not null before attempting to check the StatusCode
To test this fix, temporarily set your team account to a non-existent (or unavailable - E.G. behind VPN) url.

Adding better error handling when response is null

---

.docs/Add-VSTeamProject.md
.docs/Get-VSTeamProcess.md
.docs/params/processName.md
.docs/synopsis/Get-VSTeamProcess.md
CHANGELOG.md
VSTeam.psd1
en-US/about_vsteam.help.txt
formats/vsteamPSDrive.format.ps1xml
src/common.ps1
src/processes.psm1
src/projects.psm1
src/teamspsdrive.ps1
unit/test/mocks/mockProcessNameDynamicParam.ps1
unit/test/processes.Tests.ps1
unit/test/projects.Tests.ps1

Add Process Template Support

---

.docs/Add-VSTeamWorkItem.md
CHANGELOG.md
README.md
VSTeam.psd1
docs/Add-VSTeamProject.md
docs/Add-VSTeamWorkItem.md
docs/Get-VSTeamWorkItem.md
docs/Team.md
docs/readme.md
src/workitems.psm1
unit/test/workitem.Tests.ps1

Add parameter to Add-VSTeamWorkItem to support setting parent work item. This is based on the info in issue https://github.com/DarqueWarrior/vsteam/issues/98 and should resolve this issue.

 Add parameter to Add-VSTeamWorkItem to support setting parent work item

---

.docs/Set-VSTeamAccount.md
CHANGELOG.md
Source/Public/Set-VSTeamAccount.ps1
Source/VSTeam.psd1

Switching from Write-Host to Write-Output messed up the out of -Drive on Set-VSTeamAcount

Fixed issue with output when mapping drive with Set-VSTeamAccount

---

.docs/Set-VSTeamAccount.md
CHANGELOG.md
Source/VSTeam.psd1
Source/en-US/VSTeam-Help.xml
docs/Set-VSTeamAccount.md

Change from Set to Add-VSTeamProfile

---

Source/Public/Set-VSTeamAccount.ps1

when frequently changing accounts/switching to a new collection, for example when iterating through collections, cache becomes invalid. meaning that in case collection has changed, the cache contains wrong list of projects and it needs to be updated.
so we need to invalidate cache each time we switch account

invalidate cache on account chnage

---

.docs/Get-VSTeamPullRequest.md
CHANGELOG.md
Source/VSTeam.psd1

Documentation for Get-VSTeamPullRequest was using the Synopsis and Description for Get-VSTeamWorkItem

Get-VSTeamPullRequest documentation was linking to Get-VSTeamWorkItem documentation

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
Build-Module.ps1
README.md

Following things I tried to improve:
* When I am programming with the module I found it somehow fast if I could filter unit the unit tests. So I added a parameter
* documented parameters of `Build-Module.ps1` in code and for README.MD
* removed references to update the `.PSD1` file in the PR template as well as in the contribution doc, since it does not seem to be needed anymore, because it is generated automatically.
* added the resulting XML called `coverage.xml` to the gitignore file
none needed.

Documentation, Build scripts and get-started improvements

---

build/integrationTests.yml

Force install of VSTeam Module.
I've seen that it failed on the `Install VSTeam Module` step recently (The build that is currently listed on the "Build" badge on the README is failing on this)
Fixes #248
(not necessary)

Force install of VSTeam Module

---

.docs/Get-VSTeamGitStats.md
.docs/synopsis/Get-VSTeamGitStats.md
CHANGELOG.md
Source/Public/Get-VSTeamGitStats.ps1
Source/VSTeam.psd1
unit/test/Get-VSTeamGitStats.Tests.ps1

Add Get-VSTeamGitStats

---

.docs/Add-VSTeamUserEntitlement.md
CHANGELOG.md
Source/Public/Add-VSTeamUserEntitlement.ps1
Source/Public/Update-VSTeamUserEntitlement.ps1
Source/VSTeam.psd1
integration/test/010_projects.Tests.ps1
unit/test/usersentitlement.Tests.ps1

Add support for licensingSource and msdnLicenseType for User Entitlements
Fixes #106

Add support for licensingSource and msdnLicenseType for User Entitlements

---

.docs/Add-VSTeamPullRequest.md
.docs/Update-VSTeamPullRequest.md
.docs/synopsis/Add-VSTeamPullRequest.md
.docs/synopsis/Update-VSTeamPullRequest.md
CHANGELOG.md
Source/Public/Add-VSTeamPullRequest.ps1
Source/Public/Update-VSTeamPullRequest.ps1
Source/VSTeam.psd1
unit/test/Add-VSTeamPullRequest.Tests.ps1
unit/test/Update-VSTeamPullRequest.Tests.ps1
unit/test/sampleFiles/updatePullRequestResponse.json

Add Update-VSTeamPullRequest
Add Add-VSTeamPullRequest
Fixes #120 
Fixes #131

Add Update-VSTeamPullRequest and Add-VSTeamPullRequest

---

unit/test/membership.Tests.ps1

Membership tests lack "-and" operator. I did occasionally get wrong results like this:
```
Context Test-VSTeamMembership
[-] Should test membership 18ms
Expected Invoke-RestMethod in module VSTeam to be called 1 times exactly but was called 2 times
22:             Assert-MockCalled Invoke-RestMethod -Exactly 1 -ParameterFilter {
at <ScriptBlock>, C:\MIZE\DEV\GitHub\vsteam\unit\test\membership.Tests.ps1: line 22
```
- [-] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [-] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [-] [Update CHANGELOG.md](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
(No need for those)

Fix membership tests (add -and)

---

.docs/Get-VSTeamGitCommit.md
.docs/synopsis/Get-VSTeamGitCommit.md
CHANGELOG.md
Source/Classes/VSTeamGitCommitRef.ps1
Source/Classes/VSTeamGitUserDate.ps1
Source/Classes/_classes.json
Source/Public/Get-VSTeamGitCommit.ps1
Source/formats/Team.GitCommitRef.TableView.ps1xml
Source/formats/Team.GitUserDate.TableView.ps1xml
Source/formats/_formats.json
unit/test/Get-VSTeamGitCommit.Tests.ps1

Add Get-VSTeamGitCommit to retrieve git commits

Add Get-VSTeamGitCommit

---

.docs/Get-VSTeamGitRef.md
CHANGELOG.md
Source/Public/Get-VSTeamGitRef.ps1
Source/VSTeam.psd1
unit/test/refs.Tests.ps1

Add -Filter, -FilterContains, -Top and -ContinuationToken to Get-VSTeamGitRefs

Add -Filter, -FilterContains, -Top and -ContinuationToken to Get-VSTeamGitRefs

---

CHANGELOG.md
Source/Public/Remove-VSTeamAccessControlEntry.ps1
Source/VSTeam.psd1
docs/Remove-VSTeamAccessControlEntry.md
unit/test/Remove-VSTeamAccessControlEntry.Tests.ps1

This pull request adds the Remove-VSTeamAccessControlEntry function. This function removes one or more specified descriptors from an ACL inside the specified security namespace. This function accepts pipeline input for the namespace ID, or a properly constructed VSTeamSecurityNamespace object from which it can extract the namespace ID. Help and Unit tests are included.
- [Complete] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [Complete] [Write Unit Test](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-unit-test)
- [Complete] [Update VSTeam.psd1](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#add-a-format-file)
- [Complete] [Update …

Remove-VSTeamAccessControlEntry

---

Source/Private/applyTypes.ps1

This fixes a bug in `Get-VSTeamBuildArtifact` where an error is returned because the API returns an extra record along with the list of artifacts that is called 'build.sourcelabel' and contains a URL but no "properties" object.
This PR stops the error by excluding any build artifact records returned by the API that don't contain a "properties" object from getting the build artifact specific type names applied. The result is still returned to the user however.
Alternatively if we think it would be better to exclude this result entirely, then it could instead be filtered out in the `Get-VSTeamBuildArtifact` function.

Fix for #148

---

.docs/Update-VSTeamAgent.md
.docs/synopsis/Update-VSTeamAgent.md
CHANGELOG.md
Source/Public/Update-VSTeamAgent.ps1
unit/test/agents.Tests.ps1

Adds a new function which allows to update the agent version.

Added Update-VSTeamAgent to update agent version

---

.docs/Stop-VSTeamBuild.md
.docs/synopsis/Stop-VSTeamBuild.md
CHANGELOG.md
Source/Public/Stop-VSTeamBuild.ps1
unit/test/Stop-VSTeamBuild.Tests.ps1

- Adds a new function Stop-VSTeamBuild which allows cancelling a build using the build id.
Closes #206

Adds a new function Stop-VSTeamBuild

---

Build-Module.ps1

Build-Module.ps1 has code to install Pester 5 if it is not present.  That code exists after the import of the Pester module happens.
If no version of the Pester module is present, the script would error before installing.
If any version earlier than 5.0.0.x of the Pester module was available, it would be loaded before the install was attempted and then error when attemping to access the static property of `[PesterConfiguration]::Default`.
This PR changes the order to
* Check for a version of Pester 5.*
* If there is no Pester 5 installed, then install Pester 5 from the PowerShell Gallery
* Import Pester with a minimum version of 5.0.0
- [⛔] [Write Help](https://github.com/DarqueWarrior/vsteam/blob/master/.github/CONTRIBUTING.md#write-help)
- [⛔] [Write Unit …

Update order on installing Pester from Build-Module.  

---

.docs/Get-VSTeamPullRequest.md
CHANGELOG.md
Source/Public/Get-VSTeamPullRequest.ps1
Source/en-US/VSTeam-Help.xml
docs/Get-VSTeamPullRequest.md
unit/test/Get-VSTeamPullRequest.Tests.ps1

Currently Get-VsTeamPullRequest does not offer a way to get the commits of a specific pull request. Here's a simple implementation that works fine for me with Azure DevOps Server (on-premise). 
- Not sure if simply adding `RepositoryId` to the ById parameter set is the best approach.
- Do I need a types file for the git commit ref? ([msdn](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/get%20pull%20request?view=azure-devops-server-rest-5.0#gitcommitref))
- Since the pull request ID is only known after I create this, I guess I should update the changelog and rebase afterwards? :-) 
- Trying to run the Script Analyzer results in:
```
Invoke-ScriptAnalyzer: C:\dev\OpenSource\vsteam\Build-Module.ps1:149:9
Line |
149 |     $r = Invoke-ScriptAnalyzer -Path $output …
```

Adds IncludeCommits switch to Get-VSTeamPullRequest
